### PR TITLE
GUACAMOLE-781: CS Translation updated

### PR DESCRIPTION
**Pull request by Vict0rC**
GUACAMOLE-781: Corrections and additions to Czech translation

### CODE REVIEW

**Comment by odolezal** [comment]
Please review this pull request.

Thanks.

**Review by necouchman — CHANGES_REQUESTED** [review]
The changes themselves look fine to me - my only request is that the commit message be updated to be a little more useful in its content.  See the following page that Mike dug up that has suggestions and examples - good and bad - of commit messages:

https://www.codelord.net/2015/03/16/bad-commit-messages-hall-of-shame/

**Comment by Vict0rC** [comment]
I have no idea how to describe it better :-( Sorry :-(
Could you please advice better description?
Thank you...

**Comment by necouchman** [comment]
> I have no idea how to describe it better

Something like:

GUACAMOLE-781: Corrections and additions to Czech translation

Doesn't have to be fancy, just something that will make it easier when looking through a commit log to see what the point of the changes was.

**Comment by necouchman** [comment]
@Vict0rC Would like to get these translation updates added into the code - can you update the commit message as requested?

**Comment by Vict0rC** [comment]
GUACAMOLE-781: Corrections and additions to Czech translation

**Pull request closed without merging**
