### PR TITLE
GUACAMOLE-980: used tomcat-jre8 Docker-Image seems to be deprecated

### PR DESCRIPTION
**Pull request by asutosh936**

### CODE REVIEW

**Comment by benrubson** [comment]
Let's go ahead with this ?
As it seems to be a prerequisite before going further with #469...

@mike-jumper, without @asutosh936 response, perhaps you can update the commit message by yourself when merging the PR ?

Many thx 👍

**Comment by mike-jumper** [comment]
> ... perhaps you can update the commit message by yourself when merging the PR?

As a rule, no. It is self-defeating for an open source project to step in and take over for a contributor, particularly regarding compliance with contribution guidelines, regardless of how small that change might be. I made the mistake of stepping in on behalf of contributors in the early days of the project (before the move to the ASF), back when I was too shy to ask contributors to make minor changes themselves, and it was horrible.

If GUACAMOLE-980 becomes critical and there is no movement on this PR, then yes, we might step in, make the change ourselves via a new PR and close this one. I don't think we're at that point yet.

**Comment by benrubson** [comment]
OK, thank you @mike-jumper for your detailed explanation, understood 👍 :)

**Comment by asutosh936** [comment]
@mike-jumper - Have updated commit message. Please review and merge.

**Comment by necouchman** [comment]
@asutosh936 - You've updated the PR title, but not the commit message.  Commit message still lacks the ":" between the JIRA issue number and the message.

**Comment by asutosh936** [comment]
Looks like it is having some issues, have raised separate PR for the same with correct message with `:`.

PR: https://github.com/apache/guacamole-client/pull/553

Once [PR](https://github.com/apache/guacamole-client/pull/553) is merged, will close current PR.

**Comment by necouchman** [comment]
Merged the other pull request.

**Pull request closed without merging**
