### PR TITLE
GUACAMOLE-526: Correct redirect issue with CAS module

### PR DESCRIPTION
**Pull request by necouchman**
These changes clean up code and correct a minor typo that caused the CAS redirect to fail.

### CODE REVIEW

**Comment by mike-jumper** [comment]
These changes look good in principle. Glad to hear that all seems to work now, but I think we should understand why lacking these changes fix things before calling the problem solved.

**Comment by mike-jumper** [comment]
I don't have a CAS handy, but I'll try making the opposite of these changes to OpenID and see if the same breakage occurs. Hopefully it does and the underlying issue will suddenly make sense.

**Comment by mike-jumper** [comment]
So, I can reproduce this even with OpenID just by adding `ngRoute` to the dependencies of the module associated with the field. Not sure why yet, but doing so results in the following error:

https://code.angularjs.org/1.6.9/docs/error/$injector/unpr?p0=$rootElementProvider%20%3C-%20$rootElement%20%3C-%20$location%20%3C-%20$route%20%3C-%20$location

This error occurs within `formService.insertFieldElement()` as an exception, resulting in the field insertion promise failing, causing the field controller to apply and resulting in the "Failed to retrieve field with type (blah)" warning.

**Comment by mike-jumper** [comment]
It seems that the manner in which the injector is created for field types means that `$rootElementProvider` is not available for injection in the context of that field. This is generally OK, but `ngRoute` transitively depends on `$rootElementProvider`. Since `$rootElementProvider` cannot be injected within the context of a field type, no field type can depend on `ngRoute` without causing this error.

**Comment by mike-jumper** [comment]
@necouchman - as GUACAMOLE-526 is an issue in 1.0.0, please update the merge base to `staging/1.0.0`.

**Comment by necouchman** [comment]
Merge base updated.

**Comment by necouchman** [comment]
> Since $rootElementProvider cannot be injected within the context of a field type, no field type can depend on ngRoute without causing this error.

Hmmm...that seems like it could be a problematic limitation.  We don't have anything, yet, that depends on both registering a field type and modifying routes, but it seems like it isn't too much of a stretch to imagine that the scenario could arise?

**Comment by necouchman** [comment]
> You can't include ngRoute as a dependency on a module defining a field type, but you can still rely on index already depending on ngRoute.

Aha.  Good to know.

**Pull request merged**
