### PR TITLE
GUACAMOLE-987: Set ldap-user-attributes via env variable

### PR DESCRIPTION
**Pull request by bprfh**
Set the ldap-user-attributes if the corresponding LDAP_USER_ATTRIBUTES is set.

### CODE REVIEW

**Comment by necouchman** [comment]
@bprfh: Thanks for the fix.  I'm good with the actual change; however, the pull request and commit messages need to have the JIRA issue prepended to them.  Also, I'm not sure this is properly a "fix" - it isn't a bug, just a minor enhancement.

**Comment by bprfh** [comment]
Ahh, sorry I didn't know that.
Can I just close the request and resubmit it with the correct name?
Title would be "GUACAMOLE-987: ldap-user-attributes is not set via an env variable" ?
Or:
"GUACAMOLE-987: set ldap-user-attributes via  env variable" ?

You are right, the jiraa issue already has "enchancement".

**Comment by necouchman** [comment]
You can either close and resubmit a new request, or just edit this one.  Whatever way is easier for you.

**Comment by bprfh** [comment]
@necouchman renamed, thanks for the awesome project!

**Comment by necouchman** [comment]
@bprfh: Your commit message still needs the "GUACAMOLE-987:" prefix on it.

**Comment by bprfh** [comment]
@necouchman Ok I force pushed the right commit, is that ok?

**Pull request merged**
