### PR TITLE
GUACAMOLE-569: add Simplified Chinese translation

### PR DESCRIPTION
**Pull request by FlyingOE**
1. Add translation for Simplified Chinese
2. Fix minor typo error in English translation

### CODE REVIEW

**Comment by FlyingOE** [comment]
Yes, that's right. US English layout is indeed the most commonly used keyboard in China. To actually input Chinese characters, one need to use an IME software, as no hardware keyboard can support the vast number of characters in Chinese.

**Comment by necouchman** [comment]
Okay, cool.

@mike-jumper Just to verify, there's no concerns with merging this into master, right, with the 1.0.0 release in progress?  I'm pretty sure that's the point of the separate branches, but just want to make sure - again, been too long and I can't remember what all the caveats are.

**Comment by mike-jumper** [comment]
> Just to verify, there's no concerns with merging this into master, right, with the 1.0.0 release in progress?

@necouchman - nope, no need to worry. The point of having the staging branch is indeed to insulate the contents of the release from any other in-progress changes, and to allow those changes to continue without being blocked until the release is out.

Just be sure not to merge non-1.0.0 changes to `staging/1.0.0`. This one just goes to `master`. ;)

> Yes, that's right. US English layout is indeed the most commonly used keyboard in China. To actually input Chinese characters, one need to use an IME software, as no hardware keyboard can support the vast number of characters in Chinese.

If this is the case, and `zh-cn-qwerty.json` is truly identical to the US one, then we should represent that fact by referencing `en-us-qwerty.json` rather than duplicate things.

**Comment by necouchman** [comment]
> Just be sure not to merge non-1.0.0 changes to staging/1.0.0. This one just goes to master. ;)

Yep, got it.  Thanks for confirming all of that - what I thought, but wanted to make sure.

> If this is the case, and zh-cn-qwerty.json is truly identical to the US one, then we should represent that fact by referencing en-us-qwerty.json rather than duplicate things.

Makes sense.  How does @FlyingOE go about referencing en-us-qwerty.json?

**Comment by mike-jumper** [comment]
> Makes sense. How does @FlyingOE go about referencing en-us-qwerty.json?

Just by pointing the `CLIENT.URL_OSK_LAYOUT` string to the `layouts/en-us-qwerty.json` file. For example:

https://github.com/apache/guacamole-client/blob/0e856d7a212135d71ecfeef19270e4ff534dbc04/guacamole/src/main/webapp/translations/en.json#L145

The relevant line in the Simplified Chinese translation is:

https://github.com/FlyingOE/guacamole-client/blob/fa6a256f0067c8b106bc1f93a34d256470097427/guacamole/src/main/webapp/translations/zh.json#L145

**Comment by necouchman** [comment]
Ah, nice.  @FlyingOE can you make this change, and remove the zh-cn-qwerty.json file?

**Comment by necouchman** [comment]
Looks good.  @mike-jumper any other concerns?

**Comment by mike-jumper** [comment]
Nope. Looks good to me.

**Pull request merged**
