### PR TITLE
GUACAMOLE-759: Update French translation

### PR DESCRIPTION
**Pull request by jcharaoui**
Building upon PR #390 which seems abandoned, I made further improvements to the French translation by fixing typos, ensuring more consistency and adding any missing translations.

### CODE REVIEW

**Comment by necouchman** [comment]
@jcharaoui: Thank you for contributing these changes!  Overall things look pretty good.  One thing that does need to be fixed is the commit messages - all commit messages should have the JIRA issue in them (GUACAMOLE-759: ), and the commit messages should be meaningful.  You can probably squash many or most of these commits together - you don't need quite so many for these changes.

**Comment by jcharaoui** [comment]
One thing I wanted to make sure was to credit @felfell for their previous commit, I'll have to see if I can do that while still squashing / amending the rest.

**Comment by jcharaoui** [comment]
@necouchman There you go, squashed most commits and reworded to include the issue number.

**Comment by necouchman** [comment]
@jcharaoui: A couple more things:
* This issue is slated to be fixed in 1.2.0, so I've changed the base to `staging/1.2.0`.  However, this has resulted in a bunch of extra commits being pulled in.  Could you please rebase these on top of `staging/1.2.0` and force push?
* The commit messages could be improved a bit - I know you were trying to keep the contributions from #390, which is great, but if you could update the commit messages a bit to be more descriptive, that would be great.

**Comment by jcharaoui** [comment]
@necouchman Hopefully this does it! Le me know if you need any more changes.

**Comment by jlabegg** [comment]
Hello,
I've installed guacamole & some of the modules via the installation script of Zer0CoolX (nice script!)
Now, playing with that, i've found 2 things to say, and propose my help.
1°) the french translation of guacamole in the stable 1.2.0 miss some translations compared to the english one. I could make a point on the diffs, or i may try to fully translate it directly from the jar.
2°) there is no french translation of the TOTP guacamole module . Once again, i could try to translate that.

Thank you for this amasing tool.

**Comment by necouchman** [comment]
@jlabegg 
First, please avoid commenting on closed/merged pull requests - this is not a support forum, and the audience will be very limited.

Regarding the French translations - we try our best to provide accurate translations, but rely heavily on the community for translations, so any contribution you can provide would be welcome.  If you'd like to contribute to the French translation, you need to follow the contribution guidelines (http://guacamole.apache.org/open-source/), mainly:
* Create a JIRA issue for tracking the changes (separate from this one, as this has been closed)
* Fork the code and make the changes.  Make sure commit messages include the JIRA issue as you see, here.
* Submit a pull request for review, again with the pull request having the JIRA issue.

Regarding further help or questions, please subscribe and post to one of the mailing lists:
http://guacamole.apache.org/support/

**Pull request merged**
