### PR TITLE
GUACAMOLE-1860: fix typos in env variables

### PR DESCRIPTION
**Pull request by mazlumtoprak**
PR according to https://issues.apache.org/jira/browse/GUACAMOLE-1860

### CODE REVIEW

**Comment by mike-jumper** [comment]
Thanks @mazlumtoprak! Can you rebase against the `staging/1.5.4` branch? We can pull this into our next bugfix release.

**Comment by necouchman** [comment]
Ping @mazlumtoprak - any chance you could rebase this?

**Comment by mazlumtoprak** [comment]
Hey @mike-jumper & @necouchman,

Apologies for the delay in my response. I wanted to ensure that the rebase was executed correctly and got a bit insecure, when I received a lot of merge conflicts.

On my local repo I now fetched the latest `staging/1.5.4` and committed my changes into that, now merging to master. If you'd have a look on my PR and if everything's fine, I'll merge it to my `master`.

https://github.com/mazlumtoprak/guacamole-client/pull/1

**Comment by necouchman** [comment]
@mazlumtoprak 

Here's what I'd suggest:
* Check out the `staging/1.5.4` branch and then create a new branch from that within your fork - something like `fix-env-typo` or the like.
* Make sure your changes are committed to that branch.
* Create a new PR from that branch against the `staging/1.5.4` branch.

That'll avoid the `master` branch becoming your main development branch for PRs, which can lead to confusion and be difficult to maintain and clean up.

**Comment by mazlumtoprak** [comment]
I will close this PR due to a new one at #932

**Pull request closed without merging**
