### PR TITLE
GUACAMOLE-1411: Bump version numbers to 1.4.0.

### PR DESCRIPTION
**Pull request by mike-jumper**

### CODE REVIEW

**Review by necouchman — CHANGES_REQUESTED** [review]
If the version of `guacamole-common-js` is changing to 1.4.0, it looks like this will also need to change:

https://github.com/apache/guacamole-client/blob/dd563796e7ace1d35c8e95da41f93a785b5be657/guacamole-common-js/src/main/webapp/modules/Version.js#L22-L30

Based on the comment, there, it sounds like that constant should follow the overall `guacamole-common-js` version?

**Comment by mike-jumper** [comment]
> If the version of `guacamole-common-js` is changing to 1.4.0, it looks like this will also need to change:
> 
> https://github.com/apache/guacamole-client/blob/dd563796e7ace1d35c8e95da41f93a785b5be657/guacamole-common-js/src/main/webapp/modules/Version.js#L22-L30
> 
> Based on the comment, there, it sounds like that constant should follow the overall `guacamole-common-js` version?

Yep, good catch.

**Comment by mike-jumper** [comment]
Fixed via rebase.

**Review by necouchman — APPROVED** [review]
:shipit:

**Pull request merged**
