### PR TITLE
PROTOCOL_SSH 부분 번역 완료

### PR DESCRIPTION
**Pull request by from97**
번역 완료했습니다.

### CODE REVIEW

**Comment by necouchman** [comment]
@from97 

Thank you very much for contributing this to the project - we're always happy to have help in the translation area!

A few things that need to be adjusted, here, before moving forward:
* All pull requests need a matching Issue created in JIRA to track the improvement/bug.
* Once the JIRA issue is created, both the pull request and all commits need to be tagged with the JIRA issue (GUACAMOLE-XXXX:) - see other open pull requests for examples of this.
* You have a lot of commits in this pull request, and they can probably be squashed into a smaller number of commits, with meaningful messages.
* While you did translate the main webapp file, each of the authentication extensions has its own translation file, so it might be worth looking at those and adding those translations while you're at it, if you are so inclined.

Thanks, again!

**Comment by OctopusET** [comment]
Sorry for wrong PR. It was mistake by my club member and it's my fault. 
I didn't explain to my member how to PR properly.

I posted issue on JIRA before GUACAMOLE-1291. If it's done, I will PR here. Thank you.

**Comment by from97** [comment]
My mistake.. I was confused because it was my first PR ever.😂 Thank you @necouchman for your kind comment though, and thanks to @OctopusET also. I'll PR properly next time!

**Comment by from97** [comment]
.

**Comment by necouchman** [comment]
No worries @from97 - I see you closed this pull request, hopefully you'll open another one, soon to add this translation?

**Comment by OctopusET** [comment]
Sorry for late response. Translation is done, but test part is left. It might be done by this weekend. I will open another PR soon. Thanks.

**Pull request closed without merging**
