### PR TITLE
GUACAMOLE-1730: Add polish translation

### PR DESCRIPTION
**Pull request by henski-pl**
Adding polish translation.

### CODE REVIEW

**Review by mike-jumper — CHANGES_REQUESTED** [review]
Looks good, but please rebase to remove the merge commit.

**Comment by henski-pl** [comment]
> Looks good, but please rebase to remove the merge commit.

It should be ok now.

**Comment by henski-pl** [comment]
@mike-jumper is there something more i need to do?

**Review by mike-jumper — APPROVED** [review]
Looks good! Thanks!

**Pull request merged**
