### PR TITLE
GUACAMOLE-1584: add CSS ids to section headers on home page

### PR DESCRIPTION
**Pull request by dstndstn**
My first PR -- hopefully useful and trivial enough to be accepted!

This just adds CSS ids to the H2 section headers on the user home screen for the "Recent Connection" and "All Connections" headers.  This allowed me to customize the page by adding an extra button after the header text.

### CODE REVIEW

**Review by mike-jumper — CHANGES_REQUESTED** [review]
Looks fairly reasonable, but please use the established naming convention of `lowercase-with-dashes` for CSS classes, rather than `lowercase_with_underscores`.

**Comment by dstndstn** [comment]
Thanks, I made that change

**Comment by mike-jumper** [comment]
Thanks - please also update your commit message to follow the convention there. All commit messages should include the JIRA issue.

**Comment by dstndstn** [comment]
sorry, I messed up the Git history and I was hoping to swap in a replacement branch, but this PR got auto-closed in that process.  See #720.

**Pull request closed without merging**
